services:
  backend:
    container_name: pptx_service
    build:
      context: ./backend
    ports:
      - "5030:5030"
    environment:
      - ASPNETCORE_URLS=http://+:5030
    volumes:
      - ./backend/Templates:/app/Templates
    networks:
      - appnet

  normalizer:
    build: ./normalizer
    container_name: pptx_normalizer
    networks:
      - appnet
  frontend:
    container_name: pptx_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  appnet:
    driver: bridge